# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Publish Doc to Site

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
        token: ${{ secrets.TOKEN }}
    - name: build and push to github repo
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        ./publish-doc.sh
